"use client";
import { SessionProvider } from "next-auth/react";
import { usePathname } from "next/navigation"; // Importa el hook usePathname

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import SafeNavbarin from "./components/SafeNavbarin";
import Footer from "./components/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "ChefPick",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname(); // Obtén la ruta actual

  // Verifica si la ruta actual es /usuario o una subruta de /usuario
  const isUsuarioRoute = pathname.startsWith("/usuario");
  const isAdminRoute = pathname.startsWith("/admin");
  const isModeradorRoute = pathname.startsWith("/moderador");


  return (
    <html lang="en">
      <body id="root"
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
         {/* Renderiza el Navbar solo si no estás en una ruta de usuario */}
         {!isUsuarioRoute && !isAdminRoute && !isModeradorRoute && <SafeNavbarin />}
          {children}
          {!isUsuarioRoute  && !isAdminRoute && !isModeradorRoute && <Footer />}
        </SessionProvider>
        
      </body>
    </html>
  );
}
